name: Build, Test and Sonar Analysis

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}

      - name: Detect project folder name
        id: detect-name
        shell: pwsh
        run: |
          if (-not "${{ inputs.project-name }}") {
            $name = Split-Path $env:GITHUB_WORKSPACE -Leaf
          } else {
            $name = "${{ inputs.project-name }}"
          }
          echo "project-name=$name" >> $env:GITHUB_OUTPUT

      - name: Detect solution and project paths
        id: detect-paths
        shell: pwsh
        run: |
          $proj = "${{ steps.detect-name.outputs.project-name }}"
          $sln = Get-ChildItem -Recurse -Filter "$proj.sln" | Select-Object -First 1
          $cs  = Get-ChildItem -Recurse -Filter "$proj.csproj" | Select-Object -First 1
          if (-not $sln -or -not $cs) {
            Write-Error "Não encontrou $proj.sln ou $proj.csproj"
            exit 1
          }
          echo "solutionPath=$($sln.FullName)"  >> $env:GITHUB_OUTPUT
          echo "csprojPath=$($cs.FullName)"    >> $env:GITHUB_OUTPUT
          echo "projectFolder=$(Split-Path $cs.FullName -Parent)" >> $env:GITHUB_OUTPUT

      - name: Restore NuGet packages
        run: nuget restore "${{ steps.detect-paths.outputs.solutionPath }}"

      - name: Begin SonarCloud analysis
        shell: pwsh
        run: |
          choco install sonarscanner-msbuild-net46 --no-progress
          SonarScanner.MSBuild.exe begin `
            /k:"${{ secrets.SONAR_PROJECT_KEY }}" `
            /o:"${{ secrets.SONAR_ORGANIZATION }}" `
            /d:sonar.host.url="${{ secrets.SONAR_URL }}" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build solution
        run: msbuild "${{ steps.detect-paths.outputs.solutionPath }}" /p:Configuration=Release

      - name: Run tests using VSTest
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
          $vstest = "$vsPath\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
          $dlls = Get-ChildItem -Recurse -Filter *Tests.dll | Where-Object { $_.FullName -like "*bin*Release*" }
          foreach ($dll in $dlls) { & $vstest $dll.FullName --logger:trx }

      - name: End SonarCloud analysis
        shell: pwsh
        run: SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Download and Package with NuGet.exe
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
          ./nuget.exe pack "${{ steps.detect-paths.outputs.csprojPath }}" -Properties Configuration=Release -OutputDirectory nupkg

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: nupkg/*.nupkg
