name: Reusable NuGet Publish Workflow

on:
  workflow_call:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
           nuget-version: 5.11.0
          
      - name: Publish NuGet package
        shell: pwsh
        run: |
          $pkg = (Get-ChildItem ./nupkg/*.nupkg | Select-Object -First 1).FullName
          nuget push $pkg `
            -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
            -ApiKey "${{ secrets.GITHUB_TOKEN }}" `
            -SkipDuplicate