name: Build, Test and Sonar Analysis

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}

      - name: Detect solutions and prod projects
        id: detect-paths
        shell: pwsh
        run: |
          $sln = Get-ChildItem -Path "." -Filter "*.sln" -Recurse -File |
                 Select-Object -First 1
          if (-not $sln) {
            Write-Error "Nenhuma solução (.sln) encontrada."
            exit 1
          }
          $solutionPath = $sln.FullName

          $projectName = [System.IO.Path]::GetFileNameWithoutExtension($sln.Name)

          $csproj = Get-ChildItem -Path "." -Filter "$projectName.csproj" -Recurse -File |
                    Where-Object { $_.FullName -notmatch '\\.Test(s)?[\\/]'} |
                    Select-Object -First 1
          if (-not $csproj) {
            Write-Error "Nenhum projeto '$projectName.csproj' encontrado."
            exit 1
          }
          $csprojPath = $csproj.FullName

          echo "solutionPath=$solutionPath" >> $env:GITHUB_OUTPUT
          echo "csprojPath=$csprojPath"     >> $env:GITHUB_OUTPUT
          echo "projectName=$projectName"   >> $env:GITHUB_OUTPUT

      - name: Restore NuGet packages
        run: nuget restore

      - name: Define Sonar project key
        id: sonar-key
        shell: pwsh
        run: |
          $org = "${{ secrets.SONAR_ORGANIZATION }}"
          $repo = "${{ github.repository }}" -replace '^.*/', ''
          $projectKey = "$repo"
          echo "projectKey=$projectKey" > $env:GITHUB_OUTPUT

      - name: Ensure SonarCloud project exists
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG:   ${{ secrets.SONAR_ORGANIZATION }}
          REPO_NAME:   ${{ github.repository }}
          PROJECT_KEY: ${{ steps.sonar-key.outputs.projectKey }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -u "$SONAR_TOKEN:" \
            -d "organization=$SONAR_ORG" \
            -d "name=${{ steps.sonar-key.outputs.projectKey }}" \
            -d "project=$PROJECT_KEY" \
            https://sonarcloud.io/api/projects/create)

          if [ "$response" -eq 200 ]; then
            echo "✅ SonarCloud project successfully created: key=$PROJECT_KEY, name=$PROJECT_KEY"
          elif [ "$response" -eq 409 ]; then
            echo "ℹ️ SonarCloud project already exists: key=$PROJECT_KEY"
          else
            echo "⚠️ Failed to create SonarCloud project (HTTP $response). Continuing with the workflow."
          fi

      - name: Begin SonarCloud analysis
        shell: pwsh
        run: |
          choco install sonarscanner-msbuild-net46 --no-progress
          SonarScanner.MSBuild.exe begin `
            /k:"${{ steps.sonar-key.outputs.projectKey }}" `
            /o:"${{ secrets.SONAR_ORGANIZATION }}" `
            /d:sonar.host.url="${{ secrets.SONAR_URL }}" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build all solutions
        shell: pwsh
        run: |
          $paths = '${{ steps.detect-paths.outputs.solutionPaths }}'.Split(';')
          foreach ($sln in $paths) {
            Write-Host "Building $sln"
            msbuild $sln /p:Configuration=Release
          }

      - name: Run tests using VSTest
        shell: pwsh
        run: |
          $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath
          $vstest = "$vsPath\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
          Get-ChildItem -Recurse -Filter *Tests.dll |
            Where-Object FullName -like '*\bin\Release\*' |
            ForEach-Object { & $vstest $_.FullName --logger:trx }

      - name: End SonarCloud analysis
        shell: pwsh
        run: SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Package all prod projects
        shell: pwsh
        run: |
          if (-not (Test-Path nuget.exe)) {
            Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
          }
          $paths = '${{ steps.detect-paths.outputs.csprojPaths }}'.Split(';')
          foreach ($proj in $paths) {
            Write-Host "Packing $proj"
            .\nuget.exe pack $proj -Properties Configuration=Release -OutputDirectory nupkg
          }

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: nupkg/*.nupkg
