name: Reusable NuGet Publish Workflow

on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: 'nupkg'
        description: 'Name of the artifact containing the NuGet package'
      artifact-path:
        required: false
        type: string
        default: './nupkg'
        description: 'Path where to download the artifact'
      nuget-version:
        required: false
        type: string
        default: 'latest'
        description: 'NuGet version to use'
      package-pattern:
        required: false
        type: string
        default: '*.nupkg'
        description: 'Pattern to match NuGet packages for pushing'
      runs-on:
        required: false
        type: string
        default: 'windows-latest'
        description: 'Runner to use for this job'
    secrets:
      NUGET_API_KEY:
        required: true
        description: 'API key for NuGet repository'

jobs:
  publish:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifact .nupkg
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: ${{ inputs.nuget-version }}
          
      - name: Configure NuGet source
        run: |
          nuget sources add -Name "github" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username "${{ github.actor }}" -Password "${{ secrets.GITHUB_TOKEN }}" -StorePasswordInClearText

      - name: Push package
        run: |
          nuget push "${{ inputs.artifact-path }}/${{ inputs.package-pattern }}" -Source "github" -ApiKey "${{ secrets.NUGET_API_KEY }}" -SkipDuplicate