name: Publish ZIP to Azure Blob
on: workflow_call

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./artifact

      - name: Recriar ZIP do artefato
        shell: pwsh
        run: Compress-Archive -Path './artifact/*' -DestinationPath artefato.zip -Force

      - name: Verificar se AZURE_CREDENTIALS está definida
        shell: pwsh
        run: |
          if ([string]::IsNullOrEmpty("${{ secrets.AZURE_CREDENTIALS }}")) {
            Write-Host "AVISO: AZURE_CREDENTIALS não está definida ou está vazia!"
            exit 1
          } else {
            Write-Host "AZURE_CREDENTIALS está definida (primeiros 5 caracteres: ${{ secrets.AZURE_CREDENTIALS != '' && substring(secrets.AZURE_CREDENTIALS, 0, 5) || '' }}***)"
          }
          
          if ([string]::IsNullOrEmpty("${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}")) {
            Write-Host "AVISO: AZURE_STORAGE_CONNECTION_STRING não está definida ou está vazia!"
            exit 1
          } else {
            Write-Host "AZURE_STORAGE_CONNECTION_STRING está definida (formato correto: começa com DefaultEndpoints...)"
          }
          
      - name: Azure Login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload ZIP para Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --container-name artefatos \
              --name artefato.zip \
              --file artefato.zip \
              --overwrite
