name: Publish ZIP to Azure Blob
on: workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts    
          path: ./release

      - name: Extract project information
        id: extract-info
        shell: pwsh
        run: |
          $repoName = "${{ github.repository }}".Split('/')[1]
          echo "repo-name=$repoName" >> $env:GITHUB_OUTPUT
          
          $nupkgFile = Get-ChildItem -Path "./artifact" -Filter "*.nupkg" | Select-Object -First 1
          if ($nupkgFile) {
            $fileName = $nupkgFile.Name
            $packageName = $fileName -replace '\.([0-9]+\.)+[0-9]+\.nupkg$', ''
            echo "package-name=$packageName" >> $env:GITHUB_OUTPUT
          } else {
            echo "package-name=$repoName" >> $env:GITHUB_OUTPUT
          }

      - name: Recreate artifact ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path './release/**/*' `
            -DestinationPath artefato.zip `
            -Force

      - name: Azure Login
        uses: azure/login@v2
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload ZIP para Blob
        uses: azure/CLI@v1
        with:
          inlineScript: |
            REPO_NAME="${{ steps.extract-info.outputs.repo-name }}"
            PACKAGE_NAME="${{ steps.extract-info.outputs.package-name }}"
            
            az storage blob upload \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --container-name artifacts \
              --name "${REPO_NAME}/${PACKAGE_NAME}.zip" \
              --file artefato.zip \
              --overwrite true