name: Publish Local File Server

on:
  workflow_call:

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download NuGet package artifact
      uses: actions/download-artifact@v4
      with:
        name: nupkg
        path: ./artifact

    - name: Install NuGet CLI
      run: |
        Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
      shell: powershell

    - name: Recreate ZIP from downloaded artifact
      shell: pwsh
      run: |
        $zipName = 'artifact.zip'
        if (Test-Path $zipName) { Remove-Item $zipName }
        Compress-Archive -Path './artifact/*' -DestinationPath $zipName
        Write-Host "ZIP created at: $zipName"

    - name: Start local HTTP file server
      shell: pwsh
      run: |
        Start-Process python -ArgumentList '-m http.server 8080 --directory .' -NoNewWindow
        Start-Sleep -Seconds 5
        Write-Host "Server started at http://localhost:8080/"

    - name: Verify HTTP server is serving files
      shell: pwsh
      run: |
        Write-Host "=== HTTP index ==="
        Invoke-WebRequest -Uri http://localhost:8080/ -OutFile index.html
        Get-Content index.html
        Write-Host "=================="

    - name: Download ZIP from local server
      shell: pwsh
      run: |
        $url = 'http://localhost:8080/artifact.zip'
        Write-Host "Downloading from $url …"
        Invoke-WebRequest -Uri $url -OutFile downloaded.zip
        $info = Get-Item downloaded.zip
        Write-Host "Downloaded file: $($info.Name) — $($info.Length) bytes"